# Generated by Django 3.0.4 on 2020-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosch',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivosCh/'),
        ),
    ]
