# Generated by Django 3.0.4 on 2020-04-11 16:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosch',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to),
        ),
    ]
