# Generated by Django 3.0.4 on 2020-04-26 20:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200411_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecArchCh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to)),
                ('memoria', models.IntegerField(blank=True, null=True)),
                ('kernel', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
