# Generated by Django 3.0.4 on 2020-04-29 23:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200429_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecarchch',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to),
        ),
    ]
